from __future__ import annotations

import os
import time
import uuid


_CROCKFORD_BASE32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def _encode_base32(value: int, length: int) -> str:
    chars: list[str] = ["0"] * length
    for index in range(length - 1, -1, -1):
        value, mod = divmod(value, 32)
        chars[index] = _CROCKFORD_BASE32[mod]
    return "".join(chars)


def new_ulid() -> str:
    """Generate a ULID-compatible identifier without third-party deps."""
    timestamp_ms = int(time.time() * 1000)
    entropy_int = int.from_bytes(os.urandom(10), byteorder="big")
    return f"{_encode_base32(timestamp_ms, 10)}{_encode_base32(entropy_int, 16)}"


def generate_pilot_uuid() -> str:
    """Generate a UUID v4 for pilot-side identity bridging.

    ID Mapping (Phase 1A):
    - pilot_id:   existing ULID, used internally by the pilot
    - core_uuid:  UUID v4, generated by pilot, provisional
    - core_id:    NULL until Phase 3 (assigned by core during replay)

    Cardinality: 1 pilot_id : 1 core_uuid : 0..1 core_id
    Export: id_map.json (Phase 1.5) maps all three columns.

    These are provisional IDs. Core will mint canonical IDs during
    Phase 3 replay. The mapping is stored in id_map.json export.
    """
    return str(uuid.uuid4())

